//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 12:18:56 PM EST 
//


package com.underplex.tickay.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.underplex.infowrap.InfoSource;
import com.underplex.infowrap.MyInfoSource;
import com.underplex.tickay.jaxbinfo.ClaimRouteEntryInfo;
import com.underplex.tickay.jaxbinfo.ClaimRouteEntryInfoMe;


/**
 * <p>Java class for ClaimRouteEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClaimRouteEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="player" type="{}PlayerType"/>
 *         &lt;element name="route" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="payment" type="{}TrainType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="tunneling" type="{}TunnelingEntry" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClaimRouteEntry", propOrder = {
    "player",
    "route",
    "payment",
    "tunneling"
})
public class ClaimRouteEntry implements InfoSource<ClaimRouteEntryInfo>, MyInfoSource<ClaimRouteEntryInfoMe> {

    @XmlElement(required = true)
    protected PlayerType player;
    @XmlElement(required = true)
    protected String route;
    protected List<TrainType> payment;
    protected TunnelingEntry tunneling;
    
    @XmlTransient
    private ClaimRouteEntryInfo info;
    @XmlTransient
    private ClaimRouteEntryInfoMe myInfo;
    
    public ClaimRouteEntry(){
    	this.info = new ClaimRouteEntryInfo(this);
    }

    public ClaimRouteEntryInfo info() {
		return this.info;
	}

    public ClaimRouteEntryInfoMe myInfo() {
		return this.myInfo;
	}
        
    /**
     * Gets the value of the player property.
     * 
     * @return
     *     possible object is
     *     {@link PlayerType }
     *     
     */
    public PlayerType getPlayer() {
        return player;
    }

    /**
     * Sets the value of the player property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayerType }
     *     
     */
    public void setPlayer(PlayerType value) {
        this.player = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoute(String value) {
        this.route = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrainType }
     * 
     * 
     */
    public List<TrainType> getPayment() {
        if (payment == null) {
            payment = new ArrayList<TrainType>();
        }
        return this.payment;
    }

    /**
     * Gets the value of the tunneling property.
     * 
     * @return
     *     possible object is
     *     {@link TunnelingEntry }
     *     
     */
    public TunnelingEntry getTunneling() {
        return tunneling;
    }

    /**
     * Sets the value of the tunneling property.
     * 
     * @param value
     *     allowed object is
     *     {@link TunnelingEntry }
     *     
     */
    public void setTunneling(TunnelingEntry value) {
        this.tunneling = value;
    }

}
