//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 12:18:56 PM EST 
//


package com.underplex.tickay.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.underplex.infowrap.InfoSource;
import com.underplex.infowrap.MyInfoSource;
import com.underplex.tickay.jaxbinfo.DrawTicketsEntryInfo;
import com.underplex.tickay.jaxbinfo.DrawTicketsEntryInfoMe;


/**
 * <p>Java class for DrawTicketsEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DrawTicketsEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="player" type="{}PlayerType"/>
 *         &lt;element name="keptTicket" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="3"/>
 *         &lt;element name="returnedTicket" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="noTicketsToTake" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="error" type="{}StrategyErrorEntry" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DrawTicketsEntry", propOrder = {
    "player",
    "keptTicket",
    "returnedTicket",
    "noTicketsToTake",
    "error"
})
public class DrawTicketsEntry implements InfoSource<DrawTicketsEntryInfo>, MyInfoSource<DrawTicketsEntryInfoMe>{

    @XmlElement(required = true)
    protected PlayerType player;
    @XmlElement(required = true)
    protected List<String> keptTicket;
    protected List<String> returnedTicket;
    protected Boolean noTicketsToTake;
    protected StrategyErrorEntry error;
    
    @XmlTransient
    private DrawTicketsEntryInfo info;
    @XmlTransient
    private DrawTicketsEntryInfoMe myInfo;

    
    public DrawTicketsEntry(){
    	this.info = new DrawTicketsEntryInfo(this);
    	this.myInfo = new DrawTicketsEntryInfoMe(this);
    }
    
    public DrawTicketsEntryInfo info() {
		return this.info;
	}
    
    public DrawTicketsEntryInfoMe myInfo() {
		return this.myInfo;
	}
    
    /**
     * Gets the value of the player property.
     * 
     * @return
     *     possible object is
     *     {@link PlayerType }
     *     
     */
    public PlayerType getPlayer() {
        return player;
    }

    /**
     * Sets the value of the player property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayerType }
     *     
     */
    public void setPlayer(PlayerType value) {
        this.player = value;
    }

    /**
     * Gets the value of the keptTicket property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keptTicket property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeptTicket().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getKeptTicket() {
        if (keptTicket == null) {
            keptTicket = new ArrayList<String>();
        }
        return this.keptTicket;
    }

    /**
     * Gets the value of the returnedTicket property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the returnedTicket property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReturnedTicket().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getReturnedTicket() {
        if (returnedTicket == null) {
            returnedTicket = new ArrayList<String>();
        }
        return this.returnedTicket;
    }

    /**
     * Gets the value of the noTicketsToTake property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNoTicketsToTake() {
        return noTicketsToTake;
    }

    /**
     * Sets the value of the noTicketsToTake property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNoTicketsToTake(Boolean value) {
        this.noTicketsToTake = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link StrategyErrorEntry }
     *     
     */
    public StrategyErrorEntry getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link StrategyErrorEntry }
     *     
     */
    public void setError(StrategyErrorEntry value) {
        this.error = value;
    }

}
