//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 12:18:56 PM EST 
//


package com.underplex.tickay.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EuroFinalScoringEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EuroFinalScoringEntry">
 *   &lt;complexContent>
 *     &lt;extension base="{}FinalScoringEntry">
 *       &lt;sequence>
 *         &lt;element name="stationPoints" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EuroFinalScoringEntry", propOrder = {
    "stationPoints"
})
public class EuroFinalScoringEntry
    extends FinalScoringEntry
{

    protected int stationPoints;

    /**
     * Gets the value of the stationPoints property.
     * 
     */
    public int getStationPoints() {
        return stationPoints;
    }

    /**
     * Sets the value of the stationPoints property.
     * 
     */
    public void setStationPoints(int value) {
        this.stationPoints = value;
    }

}
