//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 12:18:56 PM EST 
//


package com.underplex.tickay.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EuroSimulationLog complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EuroSimulationLog">
 *   &lt;complexContent>
 *     &lt;extension base="{}SimulationLog">
 *       &lt;sequence>
 *         &lt;element name="euroGameEntry" type="{}EuroGameEntry" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EuroSimulationLog", propOrder = {
    "euroGameEntry"
})
public class EuroSimulationLog
    extends SimulationLog
{

    @XmlElement(required = true)
    protected List<EuroGameEntry> euroGameEntry;

    /**
     * Gets the value of the euroGameEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the euroGameEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEuroGameEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EuroGameEntry }
     * 
     * 
     */
    public List<EuroGameEntry> getEuroGameEntry() {
        if (euroGameEntry == null) {
            euroGameEntry = new ArrayList<EuroGameEntry>();
        }
        return this.euroGameEntry;
    }

}
