//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 12:18:56 PM EST 
//


package com.underplex.tickay.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FinalScoringEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FinalScoringEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="player" type="{}PlayerType"/>
 *         &lt;element name="strategyClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="regularPoints" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ticketPoints" type="{}TicketPointsEntry" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="longestTrack" type="{}PathEntry" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="finalScore" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="winner" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FinalScoringEntry", propOrder = {
    "player",
    "strategyClass",
    "regularPoints",
    "ticketPoints",
    "longestTrack",
    "finalScore",
    "winner"
})
@XmlSeeAlso({
    EuroFinalScoringEntry.class
})
public class FinalScoringEntry {

    @XmlElement(required = true)
    protected PlayerType player;
    @XmlElement(required = true)
    protected String strategyClass;
    protected int regularPoints;
    protected List<TicketPointsEntry> ticketPoints;
    protected List<PathEntry> longestTrack;
    protected int finalScore;
    protected boolean winner;

    /**
     * Gets the value of the player property.
     * 
     * @return
     *     possible object is
     *     {@link PlayerType }
     *     
     */
    public PlayerType getPlayer() {
        return player;
    }

    /**
     * Sets the value of the player property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayerType }
     *     
     */
    public void setPlayer(PlayerType value) {
        this.player = value;
    }

    /**
     * Gets the value of the strategyClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrategyClass() {
        return strategyClass;
    }

    /**
     * Sets the value of the strategyClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrategyClass(String value) {
        this.strategyClass = value;
    }

    /**
     * Gets the value of the regularPoints property.
     * 
     */
    public int getRegularPoints() {
        return regularPoints;
    }

    /**
     * Sets the value of the regularPoints property.
     * 
     */
    public void setRegularPoints(int value) {
        this.regularPoints = value;
    }

    /**
     * Gets the value of the ticketPoints property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ticketPoints property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTicketPoints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TicketPointsEntry }
     * 
     * 
     */
    public List<TicketPointsEntry> getTicketPoints() {
        if (ticketPoints == null) {
            ticketPoints = new ArrayList<TicketPointsEntry>();
        }
        return this.ticketPoints;
    }

    /**
     * Gets the value of the longestTrack property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the longestTrack property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLongestTrack().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PathEntry }
     * 
     * 
     */
    public List<PathEntry> getLongestTrack() {
        if (longestTrack == null) {
            longestTrack = new ArrayList<PathEntry>();
        }
        return this.longestTrack;
    }

    /**
     * Gets the value of the finalScore property.
     * 
     */
    public int getFinalScore() {
        return finalScore;
    }

    /**
     * Sets the value of the finalScore property.
     * 
     */
    public void setFinalScore(int value) {
        this.finalScore = value;
    }

    /**
     * Gets the value of the winner property.
     * 
     */
    public boolean isWinner() {
        return winner;
    }

    /**
     * Sets the value of the winner property.
     * 
     */
    public void setWinner(boolean value) {
        this.winner = value;
    }

}
