//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 12:18:56 PM EST 
//


package com.underplex.tickay.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.underplex.infowrap.InfoSource;
import com.underplex.infowrap.MyInfoSource;
import com.underplex.tickay.jaxbinfo.FirstDiscardEntryInfo;
import com.underplex.tickay.jaxbinfo.FirstDiscardEntryInfoMe;


/**
 * <p>Java class for FirstDiscardEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FirstDiscardEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="player" type="{}PlayerType"/>
 *         &lt;element name="firstDiscardChoiceError" type="{}StrategyErrorEntry" minOccurs="0"/>
 *         &lt;element name="keep" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="discard" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FirstDiscardEntry", propOrder = {
    "player",
    "firstDiscardChoiceError",
    "keep",
    "discard"
})
public class FirstDiscardEntry implements InfoSource<FirstDiscardEntryInfo>, MyInfoSource<FirstDiscardEntryInfoMe>{

    @XmlElement(required = true)
    protected PlayerType player;
    protected StrategyErrorEntry firstDiscardChoiceError;
    protected List<String> keep;
    protected List<String> discard;

    @XmlTransient
    private FirstDiscardEntryInfo info;
    @XmlTransient
    private FirstDiscardEntryInfoMe myInfo;
    
    public FirstDiscardEntry(){
    	this.info = new FirstDiscardEntryInfo(this);
    	this.myInfo = new FirstDiscardEntryInfoMe(this);
    }
    
    public FirstDiscardEntryInfo info() {
		return this.info;
	}
    
    public FirstDiscardEntryInfoMe myInfo() {
		return this.myInfo;
	}

    /**
     * Gets the value of the player property.
     * 
     * @return
     *     possible object is
     *     {@link PlayerType }
     *     
     */
    public PlayerType getPlayer() {
        return player;
    }

    /**
     * Sets the value of the player property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayerType }
     *     
     */
    public void setPlayer(PlayerType value) {
        this.player = value;
    }

    /**
     * Gets the value of the firstDiscardChoiceError property.
     * 
     * @return
     *     possible object is
     *     {@link StrategyErrorEntry }
     *     
     */
    public StrategyErrorEntry getFirstDiscardChoiceError() {
        return firstDiscardChoiceError;
    }

    /**
     * Sets the value of the firstDiscardChoiceError property.
     * 
     * @param value
     *     allowed object is
     *     {@link StrategyErrorEntry }
     *     
     */
    public void setFirstDiscardChoiceError(StrategyErrorEntry value) {
        this.firstDiscardChoiceError = value;
    }

    /**
     * Gets the value of the keep property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keep property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeep().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getKeep() {
        if (keep == null) {
            keep = new ArrayList<String>();
        }
        return this.keep;
    }

    /**
     * Gets the value of the discard property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the discard property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiscard().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDiscard() {
        if (discard == null) {
            discard = new ArrayList<String>();
        }
        return this.discard;
    }

}
