//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 12:18:56 PM EST 
//


package com.underplex.tickay.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GameEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GameEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="setup" type="{}SetupEntry"/>
 *         &lt;element name="firstDiscard" type="{}FirstDiscardEntry" maxOccurs="unbounded"/>
 *         &lt;element name="turn" type="{}TurnEntry" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GameEntry", propOrder = {
    "setup",
    "firstDiscard",
    "turn"
})
@XmlSeeAlso({
    EuroGameEntry.class
})
public class GameEntry {

    @XmlElement(required = true)
    protected SetupEntry setup;
    @XmlElement(required = true)
    protected List<FirstDiscardEntry> firstDiscard;
    @XmlElement(required = true)
    protected List<TurnEntry> turn;
 
    /**
     * Gets the value of the setup property.
     * 
     * @return
     *     possible object is
     *     {@link SetupEntry }
     *     
     */
    public SetupEntry getSetup() {
        return setup;
    }

    /**
     * Sets the value of the setup property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetupEntry }
     *     
     */
    public void setSetup(SetupEntry value) {
        this.setup = value;
    }

    /**
     * Gets the value of the firstDiscard property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the firstDiscard property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFirstDiscard().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FirstDiscardEntry }
     * 
     * 
     */
    public List<FirstDiscardEntry> getFirstDiscard() {
        if (firstDiscard == null) {
            firstDiscard = new ArrayList<FirstDiscardEntry>();
        }
        return this.firstDiscard;
    }

    /**
     * Gets the value of the turn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the turn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTurn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TurnEntry }
     * 
     * 
     */
    public List<TurnEntry> getTurn() {
        if (turn == null) {
            turn = new ArrayList<TurnEntry>();
        }
        return this.turn;
    }

}
