//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 12:18:56 PM EST 
//


package com.underplex.tickay.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SpecErrorEntry }
     * 
     */
    public SpecErrorEntry createSpecErrorEntry() {
        return new SpecErrorEntry();
    }

    /**
     * Create an instance of {@link PlayerDefinitionEntry }
     * 
     */
    public PlayerDefinitionEntry createPlayerDefinitionEntry() {
        return new PlayerDefinitionEntry();
    }

    /**
     * Create an instance of {@link ClaimRouteEntry }
     * 
     */
    public ClaimRouteEntry createClaimRouteEntry() {
        return new ClaimRouteEntry();
    }

    /**
     * Create an instance of {@link WipeEntry }
     * 
     */
    public WipeEntry createWipeEntry() {
        return new WipeEntry();
    }

    /**
     * Create an instance of {@link SetupPlayerEntry }
     * 
     */
    public SetupPlayerEntry createSetupPlayerEntry() {
        return new SetupPlayerEntry();
    }

    /**
     * Create an instance of {@link EuroFinalScoringEntry }
     * 
     */
    public EuroFinalScoringEntry createEuroFinalScoringEntry() {
        return new EuroFinalScoringEntry();
    }

    /**
     * Create an instance of {@link PathEntry }
     * 
     */
    public PathEntry createPathEntry() {
        return new PathEntry();
    }

    /**
     * Create an instance of {@link SetupEntry }
     * 
     */
    public SetupEntry createSetupEntry() {
        return new SetupEntry();
    }

    /**
     * Create an instance of {@link SingleTakeEntry }
     * 
     */
    public SingleTakeEntry createSingleTakeEntry() {
        return new SingleTakeEntry();
    }

    /**
     * Create an instance of {@link BuildStationEntry }
     * 
     */
    public BuildStationEntry createBuildStationEntry() {
        return new BuildStationEntry();
    }

    /**
     * Create an instance of {@link FirstDiscardEntry }
     * 
     */
    public FirstDiscardEntry createFirstDiscardEntry() {
        return new FirstDiscardEntry();
    }

    /**
     * Create an instance of {@link GameEntry }
     * 
     */
    public GameEntry createGameEntry() {
        return new GameEntry();
    }

    /**
     * Create an instance of {@link TurnEntry }
     * 
     */
    public TurnEntry createTurnEntry() {
        return new TurnEntry();
    }

    /**
     * Create an instance of {@link SimulationLog }
     * 
     */
    public SimulationLog createSimulationLog() {
        return new SimulationLog();
    }

    /**
     * Create an instance of {@link DeckDrawEntry }
     * 
     */
    public DeckDrawEntry createDeckDrawEntry() {
        return new DeckDrawEntry();
    }

    /**
     * Create an instance of {@link TakeTrainsEntry }
     * 
     */
    public TakeTrainsEntry createTakeTrainsEntry() {
        return new TakeTrainsEntry();
    }

    /**
     * Create an instance of {@link TicketPointsEntry }
     * 
     */
    public TicketPointsEntry createTicketPointsEntry() {
        return new TicketPointsEntry();
    }

    /**
     * Create an instance of {@link TunnelingEntry }
     * 
     */
    public TunnelingEntry createTunnelingEntry() {
        return new TunnelingEntry();
    }

    /**
     * Create an instance of {@link EuroGameEntry }
     * 
     */
    public EuroGameEntry createEuroGameEntry() {
        return new EuroGameEntry();
    }

    /**
     * Create an instance of {@link StrategyErrorEntry }
     * 
     */
    public StrategyErrorEntry createStrategyErrorEntry() {
        return new StrategyErrorEntry();
    }

    /**
     * Create an instance of {@link DrawTicketsEntry }
     * 
     */
    public DrawTicketsEntry createDrawTicketsEntry() {
        return new DrawTicketsEntry();
    }

    /**
     * Create an instance of {@link FinalScoringEntry }
     * 
     */
    public FinalScoringEntry createFinalScoringEntry() {
        return new FinalScoringEntry();
    }

    /**
     * Create an instance of {@link StationChoiceEntry }
     * 
     */
    public StationChoiceEntry createStationChoiceEntry() {
        return new StationChoiceEntry();
    }

    /**
     * Create an instance of {@link EuroSimulationLog }
     * 
     */
    public EuroSimulationLog createEuroSimulationLog() {
        return new EuroSimulationLog();
    }

    /**
     * Create an instance of {@link AmericaSimulationLog }
     * 
     */
    public AmericaSimulationLog createAmericaSimulationLog() {
        return new AmericaSimulationLog();
    }
    
    /**
     * Create an instance of {@link AmericaGameEntry }
     * 
     */
    public AmericaGameEntry createAmericaGameEntry() {
        return new AmericaGameEntry();
    }
}
