//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 12:18:56 PM EST 
//


package com.underplex.tickay.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlayerDefinitionEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlayerDefinitionEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="playerType" type="{}PlayerType"/>
 *         &lt;element name="strategyIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="strategyToString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlayerDefinitionEntry", propOrder = {
    "playerType",
    "strategyIdentifier",
    "strategyToString"
})
public class PlayerDefinitionEntry {

    @XmlElement(required = true)
    protected PlayerType playerType;
    @XmlElement(required = true)
    protected String strategyIdentifier;
    @XmlElement(required = true)
    protected String strategyToString;

    /**
     * Gets the value of the playerType property.
     * 
     * @return
     *     possible object is
     *     {@link PlayerType }
     *     
     */
    public PlayerType getPlayerType() {
        return playerType;
    }

    /**
     * Sets the value of the playerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayerType }
     *     
     */
    public void setPlayerType(PlayerType value) {
        this.playerType = value;
    }

    /**
     * Gets the value of the strategyIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrategyIdentifier() {
        return strategyIdentifier;
    }

    /**
     * Sets the value of the strategyIdentifier property.
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrategyIdentifier(String value) {
        this.strategyIdentifier = value;
    }

    /**
     * Gets the value of the strategyToString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrategyToString() {
        return strategyToString;
    }

    /**
     * Sets the value of the strategyToString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrategyToString(String value) {
        this.strategyToString = value;
    }

}
