//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 12:18:56 PM EST 
//


package com.underplex.tickay.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SetupEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SetupEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numberOfPlayers" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="playerDefinition" type="{}PlayerDefinitionEntry" maxOccurs="unbounded"/>
 *         &lt;element name="setupPlayer" type="{}SetupPlayerEntry" maxOccurs="unbounded"/>
 *         &lt;element name="wipe" type="{}WipeEntry" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="initialFaceUp" type="{}TrainType" maxOccurs="5" minOccurs="5"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetupEntry", propOrder = {
    "numberOfPlayers",
    "playerDefinition",
    "setupPlayer",
    "wipe",
    "initialFaceUp"
})
public class SetupEntry {

    protected int numberOfPlayers;
    @XmlElement(required = true)
    protected List<PlayerDefinitionEntry> playerDefinition;
    @XmlElement(required = true)
    protected List<SetupPlayerEntry> setupPlayer;
    protected List<WipeEntry> wipe;
    @XmlElement(required = true)
    protected List<TrainType> initialFaceUp;

    /**
     * Gets the value of the numberOfPlayers property.
     * 
     */
    public int getNumberOfPlayers() {
        return numberOfPlayers;
    }

    /**
     * Sets the value of the numberOfPlayers property.
     * 
     */
    public void setNumberOfPlayers(int value) {
        this.numberOfPlayers = value;
    }

    /**
     * Gets the value of the playerDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the playerDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlayerDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlayerDefinitionEntry }
     * 
     * 
     */
    public List<PlayerDefinitionEntry> getPlayerDefinition() {
        if (playerDefinition == null) {
            playerDefinition = new ArrayList<PlayerDefinitionEntry>();
        }
        return this.playerDefinition;
    }

    /**
     * Gets the value of the setupPlayer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the setupPlayer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSetupPlayer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SetupPlayerEntry }
     * 
     * 
     */
    public List<SetupPlayerEntry> getSetupPlayer() {
        if (setupPlayer == null) {
            setupPlayer = new ArrayList<SetupPlayerEntry>();
        }
        return this.setupPlayer;
    }

    /**
     * Gets the value of the wipe property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wipe property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWipe().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WipeEntry }
     * 
     * 
     */
    public List<WipeEntry> getWipe() {
        if (wipe == null) {
            wipe = new ArrayList<WipeEntry>();
        }
        return this.wipe;
    }

    /**
     * Gets the value of the initialFaceUp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the initialFaceUp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInitialFaceUp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrainType }
     * 
     * 
     */
    public List<TrainType> getInitialFaceUp() {
        if (initialFaceUp == null) {
            initialFaceUp = new ArrayList<TrainType>();
        }
        return this.initialFaceUp;
    }

}
