//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 12:18:56 PM EST 
//


package com.underplex.tickay.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.underplex.infowrap.InfoSource;
import com.underplex.infowrap.MyInfoSource;
import com.underplex.tickay.jaxbinfo.SingleTakeEntryInfo;
import com.underplex.tickay.jaxbinfo.SingleTakeEntryInfoMe;


/**
 * <p>Java class for SingleTakeEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SingleTakeEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="faceUpOffered" type="{}TrainType" maxOccurs="5" minOccurs="0"/>
 *         &lt;element name="deckTaken" type="{}DeckDrawEntry" minOccurs="0"/>
 *         &lt;element name="faceUpTaken" type="{}TrainType" minOccurs="0"/>
 *         &lt;element name="faceUpRevealed" type="{}DeckDrawEntry" minOccurs="0"/>
 *         &lt;element name="wipe" type="{}WipeEntry" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SingleTakeEntry", propOrder = {
    "faceUpOffered",
    "deckTaken",
    "faceUpTaken",
    "faceUpRevealed",
    "wipe"
})
public class SingleTakeEntry implements InfoSource<SingleTakeEntryInfo>, MyInfoSource<SingleTakeEntryInfoMe>{

    protected List<TrainType> faceUpOffered;
    protected DeckDrawEntry deckTaken;
    protected TrainType faceUpTaken;
    protected DeckDrawEntry faceUpRevealed;
    protected List<WipeEntry> wipe;
    
    @XmlTransient
    private SingleTakeEntryInfo info;
    @XmlTransient
    private SingleTakeEntryInfoMe myInfo;
    
    public SingleTakeEntry(){
    	this.info = new SingleTakeEntryInfo(this);
    	this.info = new SingleTakeEntryInfoMe(this);
    }
    
    public SingleTakeEntryInfo info() {
		return this.info;
	}
    
    public SingleTakeEntryInfoMe myInfo() {
		return this.myInfo;
	}
    
    /**
     * Gets the value of the faceUpOffered property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the faceUpOffered property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFaceUpOffered().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrainType }
     * 
     * 
     */
    public List<TrainType> getFaceUpOffered() {
        if (faceUpOffered == null) {
            faceUpOffered = new ArrayList<TrainType>();
        }
        return this.faceUpOffered;
    }

    /**
     * Gets the value of the deckTaken property.
     * 
     * @return
     *     possible object is
     *     {@link DeckDrawEntry }
     *     
     */
    public DeckDrawEntry getDeckTaken() {
        return deckTaken;
    }

    /**
     * Sets the value of the deckTaken property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeckDrawEntry }
     *     
     */
    public void setDeckTaken(DeckDrawEntry value) {
        this.deckTaken = value;
    }

    /**
     * Gets the value of the faceUpTaken property.
     * 
     * @return
     *     possible object is
     *     {@link TrainType }
     *     
     */
    public TrainType getFaceUpTaken() {
        return faceUpTaken;
    }

    /**
     * Sets the value of the faceUpTaken property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainType }
     *     
     */
    public void setFaceUpTaken(TrainType value) {
        this.faceUpTaken = value;
    }

    /**
     * Gets the value of the faceUpRevealed property.
     * 
     * @return
     *     possible object is
     *     {@link DeckDrawEntry }
     *     
     */
    public DeckDrawEntry getFaceUpRevealed() {
        return faceUpRevealed;
    }

    /**
     * Sets the value of the faceUpRevealed property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeckDrawEntry }
     *     
     */
    public void setFaceUpRevealed(DeckDrawEntry value) {
        this.faceUpRevealed = value;
    }

    /**
     * Gets the value of the wipe property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wipe property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWipe().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WipeEntry }
     * 
     * 
     */
    public List<WipeEntry> getWipe() {
        if (wipe == null) {
            wipe = new ArrayList<WipeEntry>();
        }
        return this.wipe;
    }

}
