//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 12:18:56 PM EST 
//


package com.underplex.tickay.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecErrorEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecErrorEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="specClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="specError" type="{}SpecErrorType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecErrorEntry", propOrder = {
    "specClass",
    "specError"
})
public class SpecErrorEntry {

    @XmlElement(required = true)
    protected String specClass;
    @XmlElement(required = true)
    protected SpecErrorType specError;

    /**
     * Gets the value of the specClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecClass() {
        return specClass;
    }

    /**
     * Sets the value of the specClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecClass(String value) {
        this.specClass = value;
    }

    /**
     * Gets the value of the specError property.
     * 
     * @return
     *     possible object is
     *     {@link SpecErrorType }
     *     
     */
    public SpecErrorType getSpecError() {
        return specError;
    }

    /**
     * Sets the value of the specError property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecErrorType }
     *     
     */
    public void setSpecError(SpecErrorType value) {
        this.specError = value;
    }

}
