//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 12:18:56 PM EST 
//


package com.underplex.tickay.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecErrorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SpecErrorType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NUMBER_OF_ITERATIONS"/>
 *     &lt;enumeration value="NUMBER_OF_PLAYERS"/>
 *     &lt;enumeration value="STRATEGY_ASSIGNMENT"/>
 *     &lt;enumeration value="EXPANSIONS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SpecErrorType")
@XmlEnum
public enum SpecErrorType {

    NUMBER_OF_ITERATIONS,
    NUMBER_OF_PLAYERS,
    STRATEGY_ASSIGNMENT,
    EXPANSIONS;

    public String value() {
        return name();
    }

    public static SpecErrorType fromValue(String v) {
        return valueOf(v);
    }

}
