//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 12:18:56 PM EST 
//


package com.underplex.tickay.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.underplex.infowrap.InfoSource;
import com.underplex.tickay.jaxbinfo.StationChoiceEntryInfo;


/**
 * <p>Java class for StationChoiceEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StationChoiceEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="player" type="{}PlayerType"/>
 *         &lt;element name="stationCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="noAvailableRoutes" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="availableRoutes" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="chosenRoute" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="error" type="{}StrategyErrorEntry" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StationChoiceEntry", propOrder = {
    "player",
    "stationCity",
    "noAvailableRoutes",
    "availableRoutes",
    "chosenRoute",
    "error"
})
public class StationChoiceEntry implements InfoSource<StationChoiceEntryInfo>{

    @XmlElement(required = true)
    protected PlayerType player;
    @XmlElement(required = true)
    protected String stationCity;
    protected Boolean noAvailableRoutes;
    protected List<String> availableRoutes;
    protected String chosenRoute;
    protected StrategyErrorEntry error;
    
    @XmlTransient
    private StationChoiceEntryInfo info;

    public StationChoiceEntry(){
    	this.info = new StationChoiceEntryInfo(this);
    }
    
    public StationChoiceEntryInfo info() {
		return this.info;
	}
    
    /**
     * Gets the value of the player property.
     * 
     * @return
     *     possible object is
     *     {@link PlayerType }
     *     
     */
    public PlayerType getPlayer() {
        return player;
    }

    /**
     * Sets the value of the player property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayerType }
     *     
     */
    public void setPlayer(PlayerType value) {
        this.player = value;
    }

    /**
     * Gets the value of the stationCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationCity() {
        return stationCity;
    }

    /**
     * Sets the value of the stationCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationCity(String value) {
        this.stationCity = value;
    }

    /**
     * Gets the value of the noAvailableRoutes property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNoAvailableRoutes() {
        return noAvailableRoutes;
    }

    /**
     * Sets the value of the noAvailableRoutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNoAvailableRoutes(Boolean value) {
        this.noAvailableRoutes = value;
    }

    /**
     * Gets the value of the availableRoutes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the availableRoutes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAvailableRoutes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAvailableRoutes() {
        if (availableRoutes == null) {
            availableRoutes = new ArrayList<String>();
        }
        return this.availableRoutes;
    }

    /**
     * Gets the value of the chosenRoute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChosenRoute() {
        return chosenRoute;
    }

    /**
     * Sets the value of the chosenRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChosenRoute(String value) {
        this.chosenRoute = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link StrategyErrorEntry }
     *     
     */
    public StrategyErrorEntry getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link StrategyErrorEntry }
     *     
     */
    public void setError(StrategyErrorEntry value) {
        this.error = value;
    }

}
