//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 12:18:56 PM EST 
//


package com.underplex.tickay.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.underplex.infowrap.InfoSource;
import com.underplex.infowrap.MyInfoSource;
import com.underplex.tickay.jaxbinfo.TakeTrainsEntryInfo;
import com.underplex.tickay.jaxbinfo.TakeTrainsEntryInfoMe;


/**
 * <p>Java class for TakeTrainsEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TakeTrainsEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="player" type="{}PlayerType"/>
 *         &lt;element name="take1" type="{}SingleTakeEntry" minOccurs="0"/>
 *         &lt;element name="take2" type="{}SingleTakeEntry" minOccurs="0"/>
 *         &lt;element name="error" type="{}StrategyErrorEntry" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TakeTrainsEntry", propOrder = {
    "player",
    "take1",
    "take2",
    "error"
})
public class TakeTrainsEntry implements InfoSource<TakeTrainsEntryInfo>, MyInfoSource<TakeTrainsEntryInfo>{

    @XmlElement(required = true)
    protected PlayerType player;
    protected SingleTakeEntry take1;
    protected SingleTakeEntry take2;
    protected StrategyErrorEntry error;
    
    @XmlTransient
    private TakeTrainsEntryInfo info;
    @XmlTransient
    private TakeTrainsEntryInfoMe myInfo;

    public TakeTrainsEntry(){
    	this.info = new TakeTrainsEntryInfo(this);
    	this.myInfo = new TakeTrainsEntryInfoMe(this);
    }
    
    public TakeTrainsEntryInfo info() {
		return this.info;
	}
    
    public TakeTrainsEntryInfoMe myInfo() {
		return this.myInfo;
	}
    
    /**
     * Gets the value of the player property.
     * 
     * @return
     *     possible object is
     *     {@link PlayerType }
     *     
     */
    public PlayerType getPlayer() {
        return player;
    }

    /**
     * Sets the value of the player property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayerType }
     *     
     */
    public void setPlayer(PlayerType value) {
        this.player = value;
    }

    /**
     * Gets the value of the take1 property.
     * 
     * @return
     *     possible object is
     *     {@link SingleTakeEntry }
     *     
     */
    public SingleTakeEntry getTake1() {
        return take1;
    }

    /**
     * Sets the value of the take1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleTakeEntry }
     *     
     */
    public void setTake1(SingleTakeEntry value) {
        this.take1 = value;
    }

    /**
     * Gets the value of the take2 property.
     * 
     * @return
     *     possible object is
     *     {@link SingleTakeEntry }
     *     
     */
    public SingleTakeEntry getTake2() {
        return take2;
    }

    /**
     * Sets the value of the take2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleTakeEntry }
     *     
     */
    public void setTake2(SingleTakeEntry value) {
        this.take2 = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link StrategyErrorEntry }
     *     
     */
    public StrategyErrorEntry getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link StrategyErrorEntry }
     *     
     */
    public void setError(StrategyErrorEntry value) {
        this.error = value;
    }

}
