//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 12:18:56 PM EST 
//


package com.underplex.tickay.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrainType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TrainType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BLACK"/>
 *     &lt;enumeration value="BLUE"/>
 *     &lt;enumeration value="RED"/>
 *     &lt;enumeration value="YELLOW"/>
 *     &lt;enumeration value="PURPLE"/>
 *     &lt;enumeration value="WHITE"/>
 *     &lt;enumeration value="GREEN"/>
 *     &lt;enumeration value="ORANGE"/>
 *     &lt;enumeration value="GRAY"/>
 *     &lt;enumeration value="LOCO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TrainType")
@XmlEnum
public enum TrainType {

    BLACK,
    BLUE,
    RED,
    YELLOW,
    PURPLE,
    WHITE,
    GREEN,
    ORANGE,
    GRAY,
    LOCO;

    public String value() {
        return name();
    }

    public static TrainType fromValue(String v) {
        return valueOf(v);
    }

}
