//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.21 at 12:18:56 PM EST 
//


package com.underplex.tickay.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.underplex.infowrap.InfoSource;
import com.underplex.tickay.jaxbinfo.WipeEntryInfo;


/**
 * <p>Java class for WipeEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WipeEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="faceUpReplacement" type="{}DeckDrawEntry" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WipeEntry", propOrder = {
    "faceUpReplacement"
})
public class WipeEntry implements InfoSource<WipeEntryInfo> {

    protected List<DeckDrawEntry> faceUpReplacement;
   
    @XmlTransient
    private WipeEntryInfo info;

    public WipeEntry(){
    	this.info = new WipeEntryInfo(this);
    }
    
    public WipeEntryInfo info() {
		return this.info;
	}
    
    /**
     * Gets the value of the faceUpReplacement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the faceUpReplacement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFaceUpReplacement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeckDrawEntry }
     * 
     * 
     */
    public List<DeckDrawEntry> getFaceUpReplacement() {
        if (faceUpReplacement == null) {
            faceUpReplacement = new ArrayList<DeckDrawEntry>();
        }
        return this.faceUpReplacement;
    }

}
